export default [
  // Mujeres
  { nombre: "Anayte Álvarez", genero: "F", pases: 1 },
  { nombre: "Allison Chay", genero: "F", pases: 1 },
  { nombre: "Elizabeth Arias", genero: "F", pases: 1 },
  { nombre: "Paula Soto", genero: "F", pases: 1 },
  { nombre: "María Fernanda Par", genero: "F", pases: 1 },
  { nombre: "Gabriela Aguilar", genero: "F", pases: 1 },
  { nombre: "Dayana Gramajo", genero: "F", pases: 1 },
  { nombre: "Emily Carreto", genero: "F", pases: 1 },
  { nombre: "Majo de León", genero: "F", pases: 1 },
  { nombre: "Merlyn Hernández", genero: "F", pases: 1 },
  { nombre: "Emely Juárez", genero: "F", pases: 1 },
  { nombre: "Katherine Mejía", genero: "F", pases: 1 },
  { nombre: "Marjorie Orozco", genero: "F", pases: 1 },
  { nombre: "Eliza Morales", genero: "F", pases: 1 },
  { nombre: "Jimena Gramajo", genero: "F", pases: 1 },
  { nombre: "Valeria Gómez", genero: "F", pases: 1 },
  { nombre: "Diana Villatoro", genero: "F", pases: 1 },
  { nombre: "Camila Mendoza", genero: "F", pases: 1 },
  { nombre: "Camila Rodas", genero: "F", pases: 1 },
  { nombre: "Isabel Valenzuela", genero: "F", pases: 1 },
  { nombre: "Camila Liu", genero: "F", pases: 1 },
  { nombre: "Paulina Córdova", genero: "F", pases: 1 },
  { nombre: "Camila Solís", genero: "F", pases: 1 },
  { nombre: "Marcela López", genero: "F", pases: 1 },
  { nombre: "Daniela Morales", genero: "F", pases: 1 },
  { nombre: "Daniela López", genero: "F", pases: 1 },
  { nombre: "Belén Barros", genero: "F", pases: 1 },
  { nombre: "Sofia Wellman", genero: "F", pases: 1 },
  { nombre: "Hannea Alonzo", genero: "F", pases: 1 },
  { nombre: "Majo Córdova", genero: "F", pases: 1 },
  { nombre: "Lesbia López", genero: "F", pases: 1 },
  { nombre: "Sofía Villatoro", genero: "F", pases: 1 },
  { nombre: "Mimi", genero: "F", pases: 1 },
  { nombre: "Lupita Maldonado", genero: "F", pases: 1 },
  { nombre: "Alejandra Xicará", genero: "F", pases: 1 },
  { nombre: "Ceci Ríos", genero: "F", pases: 1 },
  { nombre: "Cindy Hernández", genero: "F", pases: 1 },
  { nombre: "Sofía", genero: "F", pases: 1 },

  // Hombres
  { nombre: "Pablo Rodríguez", genero: "M", pases: 1 },
  { nombre: "Paolo Sánchez", genero: "M", pases: 1 },
  { nombre: "Luis Calderón", genero: "M", pases: 1 },
  { nombre: "Christian Rodríguez", genero: "M", pases: 1 },
  { nombre: "Jeriel Vásquez", genero: "M", pases: 1 },
  { nombre: "Sebastián Alvarado", genero: "M", pases: 1 },
  { nombre: "Brayan Casimiro", genero: "M", pases: 1 },
  { nombre: "André Castillo", genero: "M", pases: 1 },
  { nombre: "Pablo García-Salas", genero: "M", pases: 1 },
  { nombre: "Gabriel López", genero: "M", pases: 1 },
  { nombre: "Marcelo Peña", genero: "M", pases: 1 },
  { nombre: "Steve Tohom", genero: "M", pases: 1 },
  { nombre: "Diego Monzón", genero: "M", pases: 1 },
  { nombre: "Klaus Detlefsen", genero: "M", pases: 1 },
  { nombre: "Eder Maldonado", genero: "M", pases: 1 },
  { nombre: "Alessandro de León", genero: "M", pases: 1 },
  { nombre: "Juanca Domínguez", genero: "M", pases: 1 },
  { nombre: "Octavio Gómez", genero: "M", pases: 1 },
  { nombre: "Alan Estrada", genero: "M", pases: 1 },
  { nombre: "Kaden Guzmán", genero: "M", pases: 1 },
  { nombre: "Emiliano Chan", genero: "M", pases: 1 },
  { nombre: "Stanley Hernández", genero: "M", pases: 1 },
  { nombre: "Mario Reyes", genero: "M", pases: 1 },
  { nombre: "Jose Barrios", genero: "M", pases: 1 },
  { nombre: "Luis Diego Díaz", genero: "M", pases: 1 },
  { nombre: "Eduardo Marín", genero: "M", pases: 1 },
  { nombre: "Andrés Marín", genero: "M", pases: 1 },
  { nombre: "Jose Valdez", genero: "M", pases: 1 },
  { nombre: "Jose Montenegro", genero: "M", pases: 1 },
  { nombre: "Jose Eduardo Martínez", genero: "M", pases: 1 },
  { nombre: "Rodrigo García", genero: "M", pases: 1 },
  { nombre: "Julio Díaz", genero: "M", pases: 1 },
  { nombre: "Josué Méndez", genero: "M", pases: 1 },
  { nombre: "José Alvarado", genero: "M", pases: 1 }
]
